services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:5173"
    volumes:
      - ./project:/app/frontend/projet
    depends_on:
      - backend



  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TAVILY_API_KEY=
      - OPENAI_API_KEY=
      - OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1
